// Combines src/ into ONE file, PlanningTools.gs, that can be pasted into the Apps Script editor.
// Run: node build.js
const fs = require('fs');
const path = require('path');

const src = (f) => fs.readFileSync(path.join(__dirname, 'src', f), 'utf8').trim();

function buildHtml() {
  return src('Index.html')
    .replace('<!--STYLES-->', () => src('Styles.html'))
    .replace('<!--APP-->', () => src('App.html'));
}

function build() {
  const html = buildHtml().replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const parts = [
    `/**
 * PLANNING TOOLS — the 7 Management & Planning Tools for Google Sheets.
 *
 * HOW TO INSTALL (one file, no other files needed)
 *   1. Open a Google Sheet (a new one becomes your project).
 *   2. Extensions → Apps Script.
 *   3. Delete everything in Code.gs, paste this whole file, and click Save.
 *   4. Reload the spreadsheet. A "Planning Tools" menu appears in the menu bar.
 *   5. Planning Tools → Set up / repair project tabs (Google asks for permission once).
 *   Then read the Guide tab.
 *
 * Generated by build.js from src/. Edit the files in src/, not this file.
 *
 * @OnlyCurrentDoc
 */`,
    src('Code.gs'),
    src('Guide.gs'),
    src('Tools.gs'),
    src('Prioritization.gs'),
    src('Cpm.gs'),
    '// ================================================================ the app page (HTML, CSS, JS)\n\nvar APP_HTML = `' + html + '\n`;'
  ];
  return parts.join('\n\n') + '\n';
}

module.exports = { build, buildHtml };

if (require.main === module) {
  fs.writeFileSync(path.join(__dirname, 'PlanningTools.gs'), build());
  console.log('wrote PlanningTools.gs');
}
