#!/usr/bin/env node
/*
 * Regenerate src/cities-data.js: an offline list of ~8,600 places with IANA time zones.
 * Sources (npm): city-timezones (world cities with population and time zone) and
 * cities.json (GeoNames cities500) for every place in East Africa.
 * Usage: npm install city-timezones cities.json && node tools/make_cities.js
 */
const fs = require('fs');
const path = require('path');
const world = require('city-timezones').cityMapping.filter(c => c.timezone);
const geonames = require('cities.json');

// Single-time-zone countries whose smaller towns are added from GeoNames.
const EXTRA = { KE: 'Africa/Nairobi', UG: 'Africa/Kampala', TZ: 'Africa/Dar_es_Salaam', RW: 'Africa/Kigali', BI: 'Africa/Bujumbura', ET: 'Africa/Addis_Ababa', SS: 'Africa/Juba', SO: 'Africa/Mogadishu' };
const countryName = {};
world.forEach(c => { countryName[c.iso2] = c.country; });
countryName.SS = countryName.SS || 'South Sudan';

const rows = world
  .sort((a, b) => (b.pop || 0) - (a.pop || 0))
  .map(c => ({ name: c.city, country: c.country, region: c.province || '', lat: +c.lat, lon: +c.lng, tz: c.timezone }));
const seen = rows.map(r => r);
const near = (a, b) => a.name.toLowerCase() === b.name.toLowerCase() && Math.abs(a.lat - b.lat) < 0.2 && Math.abs(a.lon - b.lon) < 0.2;
geonames.filter(g => EXTRA[g.country]).forEach(g => {
  const r = { name: g.name, country: countryName[g.country], region: '', lat: +g.lat, lon: +g.lng, tz: EXTRA[g.country] };
  if (!seen.some(s => near(s, r))) { rows.push(r); seen.push(r); }
});

const tzs = [...new Set(rows.map(r => r.tz))];
const countries = [...new Set(rows.map(r => r.country))];
const clean = s => String(s).replace(/[|\n]/g, ' ').trim();
const lines = rows.map(r => [clean(r.name), countries.indexOf(r.country), r.lat.toFixed(3), r.lon.toFixed(3), tzs.indexOf(r.tz), r.region === r.name ? '' : clean(r.region)].join('|'));
const out = `/* Generated by tools/make_cities.js. ${rows.length} places, largest first.
 * name|country index|lat|lon|time zone index|region. Data: GeoNames (CC BY 4.0) via city-timezones and cities.json. */
(function (root) {
  'use strict';
  root.ChartCityData = {
    countries: ${JSON.stringify(countries)},
    tzs: ${JSON.stringify(tzs)},
    rows: ${JSON.stringify(lines.join('\n'))}
  };
})(typeof window !== 'undefined' ? window : globalThis);
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'cities-data.js'), out);
console.log(rows.length, 'places,', (out.length / 1024).toFixed(0), 'KB');
