#!/usr/bin/env python3
"""Regenerate src/ephem-data.js (Juno, Chiron, mean Lilith) from the Swiss Ephemeris.

Needs: pip install pyswisseph, plus the seas_*/sepl_*/semo_* files from
https://github.com/aloistr/swisseph/tree/master/ephe in SE_EPHE_PATH (default ./ephe).
"""
import os
import swisseph as swe
swe.set_ephe_path(os.environ.get('SE_EPHE_PATH', 'ephe'))
J0 = swe.julday(1800,1,1,0.0); J1 = swe.julday(2200,1,1,0.0); STEP=10.0
A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'
def enc(n):
    n+=2048; assert 0<=n<4096; return A[n>>6]+A[n&63]
out=['/* Generated by tools/make_ephemeris.py from the Swiss Ephemeris (seas/sepl files).',
     ' * Geocentric apparent tropical longitudes every 10 days (TT), 1800-2200, as centidegree deltas',
     ' * in 2-character base64. Interpolation error < 1 arcminute. */',
     '(function (root) {', "  'use strict';", f'  root.ChartEphemData = {{ j0: {J0}, step: {STEP}, bodies: {{']
for name,b in [('juno',swe.JUNO),('chiron',swe.CHIRON),('lilith',swe.MEAN_APOG)]:
    vals=[]; prev=None; jd=J0
    while jd <= J1 + STEP*3:
        v=swe.calc(jd,b)[0][0]
        if prev is not None:
            while v-prev>180: v-=360
            while v-prev<-180: v+=360
        vals.append(v); prev=v; jd+=STEP
    ints=[round(x*100) for x in vals]
    data=''.join(enc(ints[i]-ints[i-1]) for i in range(1,len(ints)))
    out.append(f"    {name}: {{ start: {ints[0]}, data: '{data}' }},")
out += ['  } };', '})(typeof window !== \'undefined\' ? window : globalThis);', '']
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'ephem-data.js'), 'w').write('\n'.join(out))
